name: solitaire_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/C1.png
   - assets/C2.png
   - assets/C3.png
   - assets/C4.png
   - assets/C5.png
   - assets/C6.png
   - assets/C7.png
   - assets/C8.png
   - assets/C9.png
   - assets/C10.png
   - assets/C11.png
   - assets/C12.png
   - assets/C13.png
   - assets/clubs.png
   - assets/D1.png
   - assets/D2.png
   - assets/D3.png
   - assets/D4.png
   - assets/D5.png
   - assets/D6.png
   - assets/D7.png
   - assets/D8.png
   - assets/D9.png
   - assets/D10.png
   - assets/D11.png
   - assets/D12.png
   - assets/D13.png
   - assets/diamonds.png
   - assets/H1.png
   - assets/H2.png
   - assets/H3.png
   - assets/H4.png
   - assets/H4.png
   - assets/H5.png
   - assets/H6.png
   - assets/H7.png
   - assets/H8.png
   - assets/H9.png
   - assets/H10.png
   - assets/H11.png
   - assets/H12.png
   - assets/H13.png
   - assets/heart.png
   - assets/S1.png
   - assets/S2.png
   - assets/S3.png
   - assets/S4.png
   - assets/S5.png
   - assets/S6.png
   - assets/S7.png
   - assets/S8.png
   - assets/S9.png
   - assets/S10.png
   - assets/S11.png
   - assets/S12.png
   - assets/S13.png
   - assets/spades.png

   
  #  - Clover/
  #  - Heart/
  #  - Spade/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
